# Generated by Django 2.2.2 on 2019-07-08 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='onibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='rotas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('descricao', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissao', models.IntegerField()),
                ('nome', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ultimalocalizacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('idOnibus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.onibus')),
            ],
        ),
        migrations.CreateModel(
            name='rotasPontos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('idRota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rotas')),
            ],
        ),
        migrations.AddField(
            model_name='onibus',
            name='idRota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rotas'),
        ),
        migrations.CreateModel(
            name='horarioRota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=5)),
                ('fim', models.CharField(max_length=5)),
                ('dias', models.CharField(max_length=7)),
                ('idRota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.rotas')),
            ],
        ),
    ]
