# Generated by Django 2.2.2 on 2019-07-10 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ultimaLocalizacaoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.usuario')),
            ],
        ),
    ]
